"""Stable structured warning contract."""

from enum import StrEnum

from pydantic import BaseModel, ConfigDict, Field


class WarningCode(StrEnum):
    STR_MISSING_RESIDUES = "STR_MISSING_RESIDUES"
    STR_MISSING_ATOMS = "STR_MISSING_ATOMS"
    STR_ALTERNATE_LOCATIONS = "STR_ALTERNATE_LOCATIONS"
    STR_NONSTANDARD_POLYMER_RESIDUES = "STR_NONSTANDARD_POLYMER_RESIDUES"
    REC_MISSING_RESIDUE = "REC_MISSING_RESIDUE"
    REC_MISSING_SIDECHAIN = "REC_MISSING_SIDECHAIN"
    REC_ALTERNATE_LOCATION = "REC_ALTERNATE_LOCATION"
    REC_NONSTANDARD_RESIDUE = "REC_NONSTANDARD_RESIDUE"
    REC_REMOTE_INCOMPLETE_RESIDUE = "REC_REMOTE_INCOMPLETE_RESIDUE"
    REC_NEAR_POCKET_GAP = "REC_NEAR_POCKET_GAP"
    REC_PROTONATION_AMBIGUOUS = "REC_PROTONATION_AMBIGUOUS"
    MEEKO_CONNECTIVITY_FAILURE = "MEEKO_CONNECTIVITY_FAILURE"
    LIG_STEREOCHEMISTRY_UNDEFINED = "LIG_STEREOCHEMISTRY_UNDEFINED"
    LIG_FORMAL_CHARGE_INFERRED = "LIG_FORMAL_CHARGE_INFERRED"
    LIG_MINIMIZATION_NOT_CONVERGED = "LIG_MINIMIZATION_NOT_CONVERGED"
    LIG_3D_COORDINATES_MISSING = "LIG_3D_COORDINATES_MISSING"
    LIG_MULTICOMPONENT_STATE = "LIG_MULTICOMPONENT_STATE"
    DOCKING_ENGINE_FAILED = "DOCKING_ENGINE_FAILED"
    DOCKING_MAPS_FROM_EQUIVALENT_SITE = "DOCKING_MAPS_FROM_EQUIVALENT_SITE"
    DOCKING_BACKEND_NOT_REPRODUCIBLE = "DOCKING_BACKEND_NOT_REPRODUCIBLE"
    VALIDATION_RMSD_FAIL = "VALIDATION_RMSD_FAIL"


class StructuredWarning(BaseModel):
    model_config = ConfigDict(extra="forbid")

    code: WarningCode
    message: str = Field(min_length=1)
    stage: str = Field(min_length=1)
    details: dict[str, object] = Field(default_factory=dict)
    recoverable: bool = True
