import { fireEvent, render, screen, waitFor, within } from "@testing-library/react";

import { MethodsPanel } from "../features/export/MethodsPanel";
import type { MethodsReport } from "../types/api";

/**
 * The Methods panel exists to let an author read what they are about to paste.
 * The properties worth pinning are the honest ones: a gap is shown as a gap,
 * the clipboard receives the markdown rather than the rendering, and prose that
 * came out of somebody else's file cannot become markup on the screen.
 */

// The real generator's output for a recorded AutoDock-GPU campaign, trimmed to
// the shapes it emits: headings, prose, a table, and a closing aside.
const MARKDOWN = [
  "## Protein preparation",
  "",
  "The receptor was prepared from the RCSB PDB entry 7AQF (resolution 1.77 Å).",
  "Missing side-chain atoms in 17 residues were rebuilt with PDBFixer 1.12.0.",
  "",
  "## Software",
  "",
  "| Software | Version | Role |",
  "| --- | --- | --- |",
  "| AutoDock-GPU | 1.6 | molecular docking |",
  "| RDKit | 2025.09.6 | descriptor calculation and filtering |",
  "",
  "*Citations for these tools are not generated by Ankora and must be added by the author.*",
].join("\n");

function report(overrides: Partial<MethodsReport> = {}): MethodsReport {
  return {
    catalog_id: "autodock_gpu_batch:a36d490c",
    generated_at: "2026-08-29T10:00:00Z",
    engine_label: "AutoDock4 · AutoDock-GPU 1.6",
    markdown: MARKDOWN,
    gaps: [],
    software: [
      { name: "AutoDock-GPU", version: "1.6", role: "molecular docking" },
      { name: "RDKit", version: "2025.09.6", role: "descriptor calculation and filtering" },
    ],
    ...overrides,
  };
}

function serve(payload: MethodsReport) {
  vi.spyOn(globalThis, "fetch").mockImplementation(async () =>
    new Response(JSON.stringify(payload), {
      status: 200, headers: { "Content-Type": "application/json" },
    }));
}

async function openDialog() {
  render(<MethodsPanel catalogId="autodock_gpu_batch:a36d490c" />);
  fireEvent.click(screen.getByRole("button", { name: "Write the Methods section" }));
  await waitFor(() => expect(screen.getByLabelText("Methods preview")).toBeInTheDocument());
}

it("renders the campaign's own prose, not a template", async () => {
  serve(report());

  await openDialog();

  expect(screen.getByRole("heading", { name: "Protein preparation" })).toBeInTheDocument();
  // Consecutive markdown lines are one paragraph, the way the manuscript reads.
  expect(screen.getByText(/7AQF \(resolution 1\.77 Å\)\. Missing side-chain atoms/))
    .toBeInTheDocument();
});

it("shows what the campaign cannot support instead of leaving it in the prose", async () => {
  serve(report({
    gaps: ["source structure record", "AutoGrid map spacing"],
    markdown: MARKDOWN.replace("7AQF", "[not recorded: source structure record]"),
  }));

  await openDialog();

  const banner = screen.getByRole("alert");
  expect(banner).toHaveTextContent("2 statements this campaign cannot support");
  expect(banner).toHaveTextContent("source structure record");
  expect(banner).toHaveTextContent("AutoGrid map spacing");
});

it("says nothing is missing only when nothing is", async () => {
  serve(report());

  await openDialog();

  expect(screen.getByText(/Every sentence below is rendered from a stored record/))
    .toBeInTheDocument();
  expect(screen.queryByRole("alert")).not.toBeInTheDocument();
});

it("copies the markdown source, not the rendering", async () => {
  serve(report());
  const writeText = vi.fn().mockResolvedValue(undefined);
  Object.defineProperty(navigator, "clipboard", { value: { writeText }, configurable: true });

  await openDialog();
  fireEvent.click(screen.getByRole("button", { name: "Copy to clipboard" }));

  await waitFor(() => expect(writeText).toHaveBeenCalledWith(MARKDOWN));
  // A manuscript takes the headings and the table pipes with it.
  expect(writeText.mock.calls[0][0]).toContain("## Software");
  await screen.findByRole("button", { name: "Copied as Markdown" });
});

it("only claims a copy that happened", async () => {
  serve(report());
  const writeText = vi.fn().mockRejectedValue(new Error("blocked"));
  Object.defineProperty(navigator, "clipboard", { value: { writeText }, configurable: true });

  await openDialog();
  fireEvent.click(screen.getByRole("button", { name: "Copy to clipboard" }));

  await waitFor(() => expect(writeText).toHaveBeenCalled());
  expect(screen.getByRole("button", { name: "Copy to clipboard" })).toBeInTheDocument();
  expect(screen.queryByRole("button", { name: "Copied as Markdown" })).not.toBeInTheDocument();
});

it("builds the software table the manuscript needs", async () => {
  serve(report());

  await openDialog();

  const table = screen.getByRole("table");
  // The `| --- |` separator is a markdown artifact, never a row.
  expect(within(table).getAllByRole("row")).toHaveLength(3);
  expect(within(table).getByRole("columnheader", { name: "Role" })).toBeInTheDocument();
  expect(within(table).getByRole("cell", { name: "2025.09.6" })).toBeInTheDocument();
});

it("shows markup from a record as text rather than rendering it", async () => {
  // Ligand and receptor names come out of files somebody else wrote.
  serve(report({
    markdown: "## Ligand preparation\n\nImported from <img src=x onerror=alert(1)>.sdf (SDF).",
  }));

  await openDialog();

  expect(screen.getByText(/<img src=x onerror=alert\(1\)>\.sdf/)).toBeInTheDocument();
  expect(document.querySelector("img")).toBeNull();
});

it("does not ask the backend until the author opens it", () => {
  const fetched = vi.spyOn(globalThis, "fetch").mockImplementation(async () =>
    new Response(JSON.stringify(report()), { status: 200 }));

  render(<MethodsPanel catalogId="autodock_gpu_batch:a36d490c" />);

  expect(fetched).not.toHaveBeenCalled();
});

it("survives a table it cannot read rather than blanking the workbench", async () => {
  // Found by adversarial audit: a table of nothing but separator rows left the
  // header undefined and threw inside render. Nothing above catches that, so
  // the whole window went blank.
  serve(report({ markdown: "## Software\n\n| --- | --- |\n" }));

  await openDialog();

  expect(screen.queryByRole("table")).not.toBeInTheDocument();
  expect(screen.getByText(/\| --- \| --- \|/)).toBeInTheDocument();
});
